/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Event = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'prizes' : IDL.Vec(IDL.Text),
  'maxParticipants' : IDL.Nat,
});
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'teamMembers' : IDL.Vec(IDL.Text),
  'event' : IDL.Text,
  'phone' : IDL.Text,
  'college' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getRegistrationsByEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'registerEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'searchEventsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Event = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'prizes' : IDL.Vec(IDL.Text),
    'maxParticipants' : IDL.Nat,
  });
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'teamMembers' : IDL.Vec(IDL.Text),
    'event' : IDL.Text,
    'phone' : IDL.Text,
    'college' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getRegistrationsByEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'registerEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'searchEventsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };