/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Event {
  'name' : string,
  'description' : string,
  'category' : string,
  'prizes' : Array<string>,
  'maxParticipants' : bigint,
}
export interface Registration {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'teamMembers' : Array<string>,
  'event' : string,
  'phone' : string,
  'college' : string,
}
export interface _SERVICE {
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getRegistrationsByEvent' : ActorMethod<[string], Array<Registration>>,
  'registerEvent' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    undefined
  >,
  'searchEventsByCategory' : ActorMethod<[string], Array<Event>>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];