/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        orbitron: ["Orbitron", "monospace"],
        jakarta: ["Plus Jakarta Sans", "sans-serif"],
        rajdhani: ["Plus Jakarta Sans", "sans-serif"],
        "mono-tech": ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
      },
      colors: {
        neon: "#00ff41",
        "neon-dim": "#00cc33",
        electric: "#8b5cf6",
        cyan: "#06b6d4",
        "bg-void": "#05050f",
        "bg-deep": "#05050f",
        "bg-dark": "#0a0a1a",
        "bg-mid": "#080816",
        "bg-card": "#0d0d20",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
      },
      boxShadow: {
        electric: "0 0 20px rgba(139,92,246,0.5), 0 0 40px rgba(139,92,246,0.2)",
        cyan: "0 0 20px rgba(6,182,212,0.5), 0 0 40px rgba(6,182,212,0.2)",
        neon: "0 0 20px rgba(0,255,65,0.5), 0 0 40px rgba(0,255,65,0.2)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        "orb-float": "orb-float 8s ease-in-out infinite",
        "neon-pulse": "neon-pulse 2s ease-in-out infinite",
        glitch: "glitch 3s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
